.PHONY: clean All

All:
	@echo "----------Building project:[ LoopsChallenge - Debug ]----------"
	@cd "LoopsChallenge" && "$(MAKE)" -f  "LoopsChallenge.mk"
clean:
	@echo "----------Cleaning project:[ LoopsChallenge - Debug ]----------"
	@cd "LoopsChallenge" && "$(MAKE)" -f  "LoopsChallenge.mk" clean
